# Generated by Django 5.2.7 on 2025-10-17 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='parts',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='parts',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
    ]
